---
#PUT here your main variable
timezone: Europe/Paris
port: 80

php_date_timezone: "UTC"
php_packages:
  - php5
  - php5-fpm
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-ldap
  - php-apc
  - php5-apcu
  - php5-pgsql
  - php5-intl
  - php5-mysql
  - php5-mongo

redis_bind: 0.0.0.0

php_memory_limit: 2G
