old_sound_rabbit_mq:
    connections:
        default:
            host:     '%old_sound_rabbit_mq.host%'
            port:     5672
            #web : 15672
            user:     '%old_sound_rabbit_mq.user%'
            password: '%old_sound_rabbit_mq.pwd%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            #keepalive: true

            # requires php-amqplib v2.4.1+
            #heartbeat: 30

            #requires php_sockets.dll
            use_socket: false # default false
    producers:
        sapar_folder_move:
            connection: default
            exchange_options:
                name: 'sapar.folder.move'
                type: direct

        sapar_folder_remove:
            connection: default
            exchange_options:
                name: 'sapar.folder.remove'
                type: direct

        media_create_media_reference:
            connection: default
            exchange_options:
                name: 'media_create_media_reference'
                #type: topic
                type: direct

        media_read_tag:
            connection: default
            exchange_options:
                name: 'media_read_tag'
                #type: topic
                type: direct

        media_update_tag:
            connection: default
            exchange_options:
                name: 'media_update_tag'
                #type: topic
                type: direct
    consumers:
        sapar_folder_move:
            connection: default
            exchange_options:
                name: 'sapar.folder.move'
                type: direct
            queue_options:
                name: 'sapar_folder_move_queue'
            callback: directory_move.consumer
            #idle_timeout: 60

        sapar_folder_remove:
            connection: default
            exchange_options:
                name: 'sapar.folder.remove'
                type: direct
            queue_options:
                name: 'sapar_folder_remove_queue'
            callback: directory_remove.consumer

        media_create_media_reference:
            connection: default
            exchange_options:
                name: 'media_create_media_reference'
                type: direct
            queue_options:
                name: 'sapar_media_create_media_reference'
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            callback: 'media_create_media_reference.consumer'

        media_read_tag:
            connection: default
            exchange_options:
                name: 'media_read_tag'
                type: direct
            queue_options:
                name: 'sapar_media_read_tag'
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            callback: 'media_read_tag.consumer'

        media_update_tag:
            connection: default
            exchange_options:
                name: 'media_update_tag'
                type: direct
            queue_options:
                name: 'sapar_media_update_tag'
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            callback: 'media_update_tag.consumer'
