
rabbit_mq_supervisor:
    worker_count:                       2 # number of workers per queue
    supervisor_instance_identifier:     instance_name
    paths:
        workspace_directory:            '%kernel.root_dir%/..'
        configuration_file:             '%kernel.root_dir%/config/supervisord.conf'
        pid_file:                       '%rb.pid_file%'
        sock_file:                      '%rb.sock_file%'
        log_file:                       '%kernel.logs_dir%/supervisord.log'
        worker_configuration_directory: '%kernel.root_dir%/config/worker/'
        worker_output_log_file:         '%kernel.logs_dir%/worker-log-%kernel.environment%.log'
        worker_error_log_file:          '%kernel.logs_dir%/worker-error-%kernel.environment%.log'
