imports:
    - { resource: config_dev.yml }

parameters:
    database_name: sf_audio_test
    database_user: travis
    database_password: ~
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    #profiler:
    #    collect: false
    #profiler: { only_exceptions: false }

web_profiler:
    #toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: false
