pyrex_admin:
    resource: "@PyrexAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

logout:
    path: /admin/logout

certification:
    resource: "@CertificationBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/certification

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:  /{_locale}/
    requirements:
        _locale: en|fr