pyrex_core_model:
    resource: "@PyrexCoreModelBundle/Resources/config/routing.xml"
    prefix:   /

pyrex_radio:
    resource: "@PyrexRadioBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
