logout:
    path: /admin/logout
    prefix:   /{_locale}/
    requirements:
        _locale: '%locale_regex%'

certification:
    resource: "@CertificationBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/certification
    requirements:
        _locale: '%locale_regex%'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:  /{_locale}/
    requirements:
        _locale: '%locale_regex%'


pyrex_admin:
    resource: "@PyrexAdminBundle/Controller/"
    #resource: "%kernel.project_dir%/src/Pyrex/AdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: "fr" }
    requirements:
        _locale: '%locale_regex%'

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /{_locale}/sonata/admin
    defaults:  { _locale: "fr" }
