#/app/config/security.yml
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, sapar_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_USER'
        sapar_db:
            entity:
                class: Pyrex\CoreModelBundle\Entity\Deejay
                #property: email
                #manager:
    encoders:
        Pyrex\CoreModelBundle\Entity\Deejay:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_area:
            pattern: ^/
            #provider: sapar_db #Give the first declared provider
            anonymous: true
            http_basic: ~
            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            form_login:
                login_path: !php/const:AppBundle\AppRouteBundle::LOGIN_NAME
                check_path: !php/const:AppBundle\AppRouteBundle::LOGIN_NAME
                default_target_path: home
            oauth:
                resource_owners:
                    facebook:      !php/const:AppBundle\AppRouteBundle::OAUTH_FACEBOOK_CHECK_PATH
                login_path:        !php/const:AppBundle\AppRouteBundle::LOGIN_NAME
                failure_path:      !php/const:AppBundle\AppRouteBundle::LOGIN_NAME
                use_forward:       false
                oauth_user_provider:
                    service: deejay_oauth_user_provider
            logout:
                path: logout
                target: !php/const:AppBundle\AppRouteBundle::LOGIN_NAME
                #default_target_path: certification_admin_index
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/((%locale_regex%)/)?(oauth/)?login/?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/((%locale_regex%)/)?oauth/redirect/facebook$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
