#/app/config/security.yml
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, sapar_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_USER'
        sapar_db:
            entity:
                class: Pyrex\CoreModelBundle\Entity\Deejay
                #property: email
                #manager:

    encoders:
        Pyrex\CoreModelBundle\Entity\Deejay:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin/
            #provider: sapar_db #Give the first declared provider
            anonymous: true
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
                #default_target_path: certification_admin_index
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
