# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    id3_wrapper.media_info:
        class: Sapar\Id3\Wrapper\BinWrapper\MediainfoWrapper
        calls:
            - [ setBinPath, ['%id3tool.mediainfo.bin%'] ]
            - [ setLogger, ['@?monolog.logger.id3_reader'] ]
    id3_wrapper.eyed3:
        class: Sapar\Id3\Wrapper\BinWrapper\Eyed3Wrapper
        calls:
            - [ setBinPath, ['%id3tool.eyed3.bin%'] ]
            - [ setLogger, ['@?monolog.logger.id3_reader'] ]
    id3_wrapper.id3v2:
        class: Sapar\Id3\Wrapper\BinWrapper\Id3v2Wrapper
        calls:
            - [ setBinPath, ['%id3tool.id3v2.bin%'] ]
            - [ setLogger, ['@?monolog.logger.id3_reader'] ]
    id3_wrapper.metaflac:
        class: Sapar\Id3\Wrapper\BinWrapper\MetaflacWrapper
        calls:
            - [ setBinPath, ['%id3tool.metaflac.bin%'] ]
            - [ setLogger, ['@?monolog.logger.id3_reader'] ]
    id3_manager:
        class: AppBundle\Id3\Id3Manager
        arguments: ['@?logger']
        calls:
            - [ addWrapper, ['@id3_wrapper.media_info'] ]
            - [ addWrapper, ['@id3_wrapper.eyed3'] ]
            - [ addWrapper, ['@id3_wrapper.id3v2'] ]
            - [ addWrapper, ['@id3_wrapper.metaflac'] ]

    subscriber.app:
        class:     AppBundle\EventListener\AppEventSubscriber
        arguments: [ '@doctrine', '@serializer', '@logger']
        tags:
          -        { name: kernel.event_subscriber }
    subscriber.lexik_form_filter.doctrine_subscriber:
        class:     AppBundle\EventListener\LexikFilterSubscriber
        tags:
          -        { name: kernel.event_subscriber }

    #Only for test
    hautelook_alice.custom_faker_generator:
        class: Faker\Generator
        factory: [ Faker\Factory, create ]
        lazy: true
        arguments:
            - '%hautelook_alice.locale%'
        calls:
            - [ seed, [ '%hautelook_alice.seed' ] ]
    faker.avd_item_provider:
        class: AppBundle\Faker\Provider\AvItemProvider
        arguments: [ '@hautelook_alice.custom_faker_generator' ]
        tags: [ { name: hautelook_alice.faker.provider } ]

    alice.processor.user:
        class: AppBundle\DataFixtures\Processor\UserProcessor
        arguments: ["@security.password_encoder"]
        tags: [ { name: hautelook_alice.alice.processor } ]
