services:
    directory_move.consumer:
        class: AppBundle\RabbitMq\Consumer\DirectoryMoveConsumer
        arguments: ['@monolog.logger.consumer', '@event_dispatcher']
        tags:
          - { name: monolog.logger, channel: directory.move }
        calls:
          - [ setContainer, [ '@service_container' ] ]

    directory_remove.consumer:
        class: AppBundle\RabbitMq\Consumer\DirectoryRemoveConsumer
        arguments: ['@monolog.logger.consumer', '@event_dispatcher']
        tags:
          - { name: monolog.logger, channel: directory.remove }
        calls:
            - [ setContainer, [ '@service_container' ] ]

    media_read_tag.consumer:
        class: AppBundle\RabbitMq\Consumer\MediaReadTagConsumer
        arguments: ['@monolog.logger.consumer', '@event_dispatcher']
        tags:
          - { name: monolog.logger }
        calls:
            - [ setContainer, [ '@service_container' ] ]

    media_update_tag.consumer:
        class: AppBundle\RabbitMq\Consumer\MediaUpdateTagConsumer
        arguments: ['@monolog.logger.consumer']
        tags:
          - { name: monolog.logger }
        calls:
            - [ setContainer, [ '@service_container' ] ]

    media_create_media_reference.consumer:
        class: AppBundle\RabbitMq\Consumer\MediaCreateReferenceConsumer
        arguments: ['@monolog.logger.consumer']
        tags:
          - { name: monolog.logger }
        calls:
            - [ setContainer, [ '@service_container' ] ]
