---
- name: Check for newrelic_license_key
  fail: msg="newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: Add newrelic GPG key.
  apt_key:
    url=https://download.newrelic.com/548C16BF.gpg
    state=present

- name: Add newrelic repository.
  apt_repository:
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present
  register: added_repository

- name: Update the apt cache.
  apt: update_cache=yes
  when: added_repository.changed

- name: Install New Relic PHP Agent
  apt:
    pkg: newrelic-php5
    state: latest
  notify: Run New Relic Installer

- name: Copy newrelic.ini file in fpm directory
  template:
    src: newrelic.ini.j2
    dest: "/etc/php5/fpm/conf.d/newrelic.ini"
  notify: Run New Relic Installer

- name: Copy newrelic.ini file in cli directory
  template:
    src: newrelic.ini.j2
    dest: "/etc/php5/cli/conf.d/newrelic.ini"
  notify: Run New Relic Installer

#We don't put it in the mods-available directory because the newrelic installer checks if
# /etc/php5/fpm/conf.d/newrelic.ini exists instead of the symlink 20-newrelic that would have been created if
# we have put the file in the mods-available directory
