services:
#    pyrex_admin.example:
#        class: Pyrex\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    deejay_new_registration:
        class: Pyrex\AdminBundle\EventListener\NewRegistrationEventListener
        arguments: [ '@mailer', '@app.system_email']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    deejay_new_registration_form:
        class: Pyrex\AdminBundle\Form\Type\DeejayRegistrationType
        tags:
            - { name: form.type}
