---
- name: install
  apt: name=nginx state=latest update_cache=true cache_valid_time=3600
  tags:
  - packages

- name: remove default site conf
  file: path=/etc/nginx/conf.d/default state=absent
  notify: reload-nginx

- name: remove default site conf
  file: path=/etc/nginx/sites-available/default state=absent
  notify: reload-nginx

### VAGRANT PART ####
- name: add front vhost for the vagrant
  template: src=etc/nginx/conf.d/vagrantconf dest=/etc/nginx/conf.d/main.conf
  notify: restart-nginx
  when: dev_env

######################


#### PROD STAGING PART ####
- name: add server main listener for prod environment
  template: src=etc/nginx/conf.d/prodconf dest=/etc/nginx/conf.d/main.conf
  notify: restart-nginx
  when: not dev_env

##########################

#- name: add basic http protection
#  template: src=etc/nginx/conf.d/.sapar-htpasswd dest=/etc/nginx/conf.d/.htpasswd
#  notify: restart-nginx

- name: create the nginx error log file so nginx can start without any errors
  file: path={{ path_to_nginx_error_log }} state=touch owner=www-data group=www-data

- name: create the nginx access log file so nginx can start without any errors
  file: path={{ path_to_nginx_access_log }} state=touch owner=www-data group=www-data

- name: nginx - update mime types
  copy: src=etc/nginx/mime.types dest=/etc/nginx/mime.types owner=root group=root mode=0644
  notify: restart-nginx

- name: enable service
  service: name=nginx enabled=yes state=started
