parameters:
    command.collection_dumper.class: AppBundle\Command\CollectionDumperCommand
    streamer.class: AppBundle\Service\Streamer

services:

    app.command.collection_dumper:
        class: '%command.collection_dumper.class%'
        arguments:
            - '@?logger'
        tags:
            - { name: 'console.command'}

    #Files Organizer
    app.media.media_organizer.manager:
        class: AppBundle\Organizer\MediaOrganizerManager
        arguments:
            - '@event_dispatcher'
            - '@logger'

    app.media.organizer.file_genre.rule:
        class: AppBundle\Organizer\Rules\FileGenreRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.file_month.rule:
        class: AppBundle\Organizer\Rules\FileMonthRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.file_year.rule:
        class: AppBundle\Organizer\Rules\FileYearRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.release_month.rule:
        class: AppBundle\Organizer\Rules\MediaReleaseMonthRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.release_year.rule:
        class: AppBundle\Organizer\Rules\MediaReleaseYearRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.genre:
        class: AppBundle\Organizer\Rules\MediaGenreRule
        tags: [ { name: organizer.rule } ]

    app.media.organizer.type:
        class: AppBundle\Organizer\Rules\MediaTypeRule
        tags: [ { name: organizer.rule } ]

    app.media_tag_reader:
        class: AppBundle\Service\MediaTagReader
        arguments: ['@id3_manager']

    app.media_tag_update:
        class: AppBundle\Service\MediaTagUpdate
        arguments: ['@repository.media', '@serializer']

    app.media_create_reference:
        class: AppBundle\Service\MediaCreateReference
        arguments: ['@repository.media']

    genre_stack:
        class: AppBundle\Service\GenreStack
        arguments:
            - '@doctrine'

    app.serializer_normalizer.id3metadata_normalizer:
        class: AppBundle\Serializer\Normalizer\Id3MetadataNormalizer
        public: false
        calls:
            - [ setGenreRepository, ['@repository.genre']]
            - [ setMediaRepository, ['@repository.media']]
        tags:
            - { name: serializer.normalizer }

    streamer:
        class: '%streamer.class%'
#        arguments:
#            - @logger

    app.system_email:
        class: AppBundle\Service\SystemEmail
        arguments:
            - '@swiftmailer.mailer'
            - '@templating.engine.twig'

    app.twig_extension:
        class: AppBundle\Twig\AppExtention
        arguments: ['@request_stack', '@router', '%allowed_directories%']
        public: false
        tags:
            - { name: twig.extension }
    app.form.type.no_ui_slider:
        class: AppBundle\Form\Type\NoUiSliderType
        arguments: ['@twig', '@event_dispatcher']
        tags:
            - { name: form.type }
    app.form.type.no_ui_slider_filter:
        class: AppBundle\Form\Type\NoUiSliderFilterType
        tags:
            - { name: form.type }
