<?php
/**
 * Copyright (c) 2016. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 * Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
 * Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
 * Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
 * Vestibulum commodo. Ut rhoncus gravida arcu.
 */

namespace Pyrex\CoreModelBundle\Repository;

use Pyrex\CoreModelBundle\Entity\Genre;

/**
 * GenreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends AbstractCoreRepository
{
    /**
     * @param string $name
     *
     * @return Genre
     */
    public function createIfNotExist($name)
    {
        $name = trim($name);
        $genre = $this->findOneBy(['name' => $name]);
        if (!$genre) {
            $genre = new Genre($name);
            $this->save($genre);
        }

        return $genre;
    }
}
