<?php

namespace Pyrex\CoreModelBundle\Repository;

use AppBundle\Entity\Media;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends AbstractCoreRepository
{

    /**
     * @param string $providerId
     * @return object
     */
    public static function getMediaInstanceByProviderId($providerId)
    {
        $mediaClass = Media::getProviderClass($providerId);

        return new $mediaClass();
    }

    /**
     * @param string $file
     * @param int    $providerId
     * @return Media
     */
    public function createIfNotExist($file, $providerId = null)
    {
        $media = new Media();
        if ($providerId) {
            $media = static::getMediaInstanceByProviderId($providerId);
        }
        $media->setFullPath($file);

        $this->logger->info('Search '.md5($file));
        $exist = $this->findOneBy(['fullFilePathMd5' => $media->getFullFilePathMd5()]);
        if ($exist) {
            return $exist;
        }
        
        $this->save($media);

        return $media;
    }
}
