<?php

namespace Pyrex\CoreModelBundle\Repository;

use AppBundle\Entity\Media;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends AbstractCoreRepository
{

    /**
     * @param string $providerId
     * @return object
     */
    public static function getMediaInstanceByProviderId($providerId)
    {
        $mediaClass = Media::getProviderClass($providerId);

        return new $mediaClass();
    }

    /**
     * @param string $file
     * @param int    $providerId
     * @return Media
     */
    public function createIfNotExist($file, $providerId = null)
    {
        $exist = $this->findOneBy(['fullFilePathMd5' => md5($file)]);
        if (!$exist) {
            $exist = new Media();
            if ($providerId) {
                $exist = static::getMediaInstanceByProviderId($providerId);
            }
            $exist->setFullPath($file);
            $this->save($exist);
        }

        return $exist;
    }
}
