<?php

namespace Pyrex\CoreModelBundle\Repository;

use Pyrex\CoreModelBundle\Entity\RadioHit;
use Doctrine\ORM\EntityRepository;

/**
 * RadioHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioHitRepository extends AbstractCoreRepository
{

    /**
     * @param string $artist
     * @param string $title
     * @param int    $minSimilarity
     * @return array
     */
    public function getSimilar($artist, $title, $minSimilarity = 51)
    {
        $query = $this->_em->createQuery('SELECT r FROM RadioHit r WHERE LEVENSHTEIN_RATIO(CONCAT(r.artist, \' \', title), :artistTitle) > :minSimilarity');
        $query->setParameter('artistTitle', sprintf('%s %s', $artist, $title));
        $query->setParameter('minSimilarity', $minSimilarity);

        return $query->getResult();
    }
}
