Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |v|
        v.name = "sapar-rabbitmq.dev"
        v.customize [
            "modifyvm", :id,
            "--name", "sapar-rabbitmq.dev",
            "--memory", 2048,
            "--natdnshostresolver1", "on",
            "--cpus", 2,
        ]
        #v.gui = true
    end

    config.vm.box = "bento/ubuntu-16.04"
    config.vm.box_check_update = true
    config.vm.network :private_network, ip: "11.11.11.11"
    config.ssh.forward_agent = true
    #config.ssh.private_key_path = "~/.ssh/id_rsa"
    #config.ssh.username = "yemistikris"

    #config.vm.synced_folder "./", "/vagrant", type: "nfs"
end
