---
audio_app:
  path: /var/www/audio-api/current/web
  hostname: sapar.audio
radio_app:
  path: /var/www/radio/current/web
  hostname: sapar.radio
apache_vhosts:
  - servername: "{{audio_app.hostname}}"
    documentroot: "{{audio_app.path}}"
    extra_parameters: |
          SetEnv SYMFONY_ENV dev
  - servername: "{{radio_app.hostname}}"
    documentroot: "{{radio_app.path}}"
    extra_parameters: |
          SetEnv SYMFONY_ENV dev
server:
    packages: [git, nodejs, vim]
    timezone: Europe/Paris
    locale: fr_FR.UTF-8
vagrant_local:
    vm:
      base_box: trusty64
      hostname: sapar.audio
      ip: 10.0.0.5
      memory: '2048'
mysql:
    root_password: sigipsr
    database: sf_audio_dev
    user: travis
    password: ''
    dump: ''
rabbitmq:
    user: admin
    password: sigipsr
    plugins: [rabbitmq_management, rabbitmq_management_visualiser]
zookeeper:
    version: 3.4.6
    port: '2181'
solr:
    port: '8983'
    version: 5.2.0
    cloud_mode: '1'
php:
    ppa: php5-5.6
    packages:
      - php5
      - php5-fpm
      - php5-mysql
      - php5-mcrypt
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-ldap
      - php-apc
bash_aliases:
    - { alias: 'sf', command: 'php app/console' }
    - { alias: 'sfcc', command: 'sf cache:clear' }
    - { alias: 'sfccnw', command: 'sfcc --no-warmup' }
    - { alias: 'sfl', command: 'sf list' }
    - { alias: 'sflg', command: 'sf list | grep' }
    - { alias: 'cd-audio', command: 'cd /var/www/audio-api/current/' }
    - { alias: 'cd-radio', command: 'cd /var/www/radio/current/' }
    - { alias: 'php', command: 'php -dzend_extension=xdebug.so' }
    - { alias: 'phpunit', command: 'php $(which phpunit)' }
